In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("gpt_dataset_10000.csv")

In [3]:
z1=df['Category'].unique()

In [4]:
df['Category'].value_counts()

Category
Python Developer                      1032
Cloud Engineer                        1023
Frontend Developer                    1020
Data Engineer                         1010
Full Stack Developer                  1000
DevOps Engineer                        997
Mobile App Developer (iOS/Android)     988
Backend Developer                      980
Data Scientist                         978
Machine Learning Engineer              972
Name: count, dtype: int64

In [5]:
df.isnull().sum()

Category    0
Resume      0
dtype: int64

In [6]:
df.duplicated().sum()

1

In [7]:
print(df)

                                Category  \
0     Mobile App Developer (iOS/Android)   
1                        DevOps Engineer   
2                          Data Engineer   
3                   Full Stack Developer   
4                          Data Engineer   
...                                  ...   
9995                   Backend Developer   
9996           Machine Learning Engineer   
9997                     DevOps Engineer   
9998                  Frontend Developer   
9999                  Frontend Developer   

                                                 Resume  
0     Seeking a Mobile App Developer (iOS/Android) r...  
1     Experienced DevOps Engineer with 7 years of ha...  
2     As a Data Engineer for the past 4 years, I've ...  
3     Experienced Full Stack Developer with 4 years ...  
4     Results-driven Data Engineer with a 9-year tra...  
...                                                 ...  
9995  A Backend Developer specializing in Python, No...  
9996  A

# Lowercasing

In [9]:
df['Resume']=df['Resume'].apply(lambda x:x.lower())

In [10]:
df

Category  \
0     Mobile App Developer (iOS/Android)   
1                        DevOps Engineer   
2                          Data Engineer   
3                   Full Stack Developer   
4                          Data Engineer   
...                                  ...   
9995                   Backend Developer   
9996           Machine Learning Engineer   
9997                     DevOps Engineer   
9998                  Frontend Developer   
9999                  Frontend Developer   

                                                 Resume  
0     seeking a mobile app developer (ios/android) r...  
1     experienced devops engineer with 7 years of ha...  
2     as a data engineer for the past 4 years, i've ...  
3     experienced full stack developer with 4 years ...  
4     results-driven data engineer with a 9-year tra...  
...                                                 ...  
9995  a backend developer specializing in python, no...  
9996  a machine learning engineer specializing in ml...  
9997  a devops engineer specializing in github actio...  
9998  a frontend developer specializing in react, ht...  
9999  seeking a frontend developer role. i bring 10 ...  

[10000 rows x 2 columns]

# Removing Stopwords

In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PRINCE\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')

In [14]:
df['Resume']=df['Resume'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [15]:
df

Category  \
0     Mobile App Developer (iOS/Android)   
1                        DevOps Engineer   
2                          Data Engineer   
3                   Full Stack Developer   
4                          Data Engineer   
...                                  ...   
9995                   Backend Developer   
9996           Machine Learning Engineer   
9997                     DevOps Engineer   
9998                  Frontend Developer   
9999                  Frontend Developer   

                                                 Resume  
0     seeking mobile app developer (ios/android) rol...  
1     experienced devops engineer 7 years hands-on e...  
2     data engineer past 4 years, developed deep exp...  
3     experienced full stack developer 4 years hands...  
4     results-driven data engineer 9-year track reco...  
...                                                 ...  
9995  backend developer specializing python, node.js...  
9996  machine learning engineer specializing mlops, ...  
9997  devops engineer specializing github actions, c...  
9998  frontend developer specializing react, html5, ...  
9999  seeking frontend developer role. bring 10 year...  

[10000 rows x 2 columns]

# Removing Numbers

In [17]:
df['Resume']=df['Resume'].apply(lambda x:' '.join([i for i in x.split() if not i.isdigit()]))

In [18]:
df

Category  \
0     Mobile App Developer (iOS/Android)   
1                        DevOps Engineer   
2                          Data Engineer   
3                   Full Stack Developer   
4                          Data Engineer   
...                                  ...   
9995                   Backend Developer   
9996           Machine Learning Engineer   
9997                     DevOps Engineer   
9998                  Frontend Developer   
9999                  Frontend Developer   

                                                 Resume  
0     seeking mobile app developer (ios/android) rol...  
1     experienced devops engineer years hands-on exp...  
2     data engineer past years, developed deep exper...  
3     experienced full stack developer years hands-o...  
4     results-driven data engineer 9-year track reco...  
...                                                 ...  
9995  backend developer specializing python, node.js...  
9996  machine learning engineer specializing mlops, ...  
9997  devops engineer specializing github actions, c...  
9998  frontend developer specializing react, html5, ...  
9999  seeking frontend developer role. bring years e...  

[10000 rows x 2 columns]

# Removing Punctuation

In [20]:
import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

In [21]:
df['Resume']=df['Resume'].apply(remove_punctuation)

In [22]:
df

Category  \
0     Mobile App Developer (iOS/Android)   
1                        DevOps Engineer   
2                          Data Engineer   
3                   Full Stack Developer   
4                          Data Engineer   
...                                  ...   
9995                   Backend Developer   
9996           Machine Learning Engineer   
9997                     DevOps Engineer   
9998                  Frontend Developer   
9999                  Frontend Developer   

                                                 Resume  
0     seeking mobile app developer iosandroid role b...  
1     experienced devops engineer years handson expe...  
2     data engineer past years developed deep expert...  
3     experienced full stack developer years handson...  
4     resultsdriven data engineer 9year track record...  
...                                                 ...  
9995  backend developer specializing python nodejs r...  
9996  machine learning engineer specializing mlops k...  
9997  devops engineer specializing github actions ci...  
9998  frontend developer specializing react html5 cs...  
9999  seeking frontend developer role bring years ex...  

[10000 rows x 2 columns]

In [23]:
x=df.drop(columns='Category')


In [24]:
y=df['Category']


In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
y

array([8, 4, 2, ..., 4, 5, 5])

In [28]:
df2 = pd.DataFrame(y)
z2 = df2[0].unique()
dict = {}
for i in range(len(z2)):
    dict[z2[i]] = z1[i]

dict

{8: 'Mobile App Developer (iOS/Android)',
 4: 'DevOps Engineer',
 2: 'Data Engineer',
 6: 'Full Stack Developer',
 7: 'Machine Learning Engineer',
 0: 'Backend Developer',
 1: 'Cloud Engineer',
 9: 'Python Developer',
 3: 'Data Scientist',
 5: 'Frontend Developer'}

In [29]:
z2=df2[0].unique()
z2

array([8, 4, 2, 6, 7, 0, 1, 9, 3, 5])

In [30]:
df2=pd.DataFrame(y)
df2

0
0     8
1     4
2     2
3     6
4     2
...  ..
9995  0
9996  7
9997  4
9998  5
9999  5

[10000 rows x 1 columns]

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3,stratify=y)

In [32]:
print(x_train.shape,x_test.shape)

(8000, 1) (2000, 1)


In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tfidf=TfidfVectorizer()

In [35]:
x_train=tfidf.fit_transform(x_train['Resume']).toarray()
x_test=tfidf.transform(x_test['Resume'])

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [37]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

1.0

In [38]:
y_pred

array([0, 0, 0, ..., 4, 0, 4])

In [39]:
confusion_matrix(y_test,y_pred)

array([[196,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 205,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 202,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 196,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 199,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 204,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 200,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 194,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 198,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 206]], dtype=int64)

In [40]:
import pickle
model_pkl_file = "resumeclassifier.pkl"  

with open(model_pkl_file, 'wb') as file:  
    pickle.dump(rf, file)

In [41]:
with open(model_pkl_file, 'rb') as file:  
    rf = pickle.load(file)
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

1.0

In [42]:
model_pkl_file = "tfidf.pkl"  

with open(model_pkl_file, 'wb') as file:  
    pickle.dump(tfidf, file)

In [43]:
def predict_role(text):
    # (Optional) If you have a clean_text() function, apply it
    # text = clean_text(text)

    # Transform input with TF-IDF
    vectorized_text = tfidf.transform([text])

    # Predict encoded label with RandomForest
    predicted_category = rf.predict(vectorized_text)

    # Decode to original role name
    predicted_category_name = le.inverse_transform(predicted_category)

    return predicted_category_name[0]


In [44]:
import pickle

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

In [45]:
myresume = """
Cloud Engineer
Highly skilled Cloud Engineer with 4 years of experience designing and implementing cloud-based solutions for financial services, healthcare, and e-commerce industries Proven track record in reducing downtime by 50%, increasing customer satisfaction by 20%, and reducing cloud costs by 30%. Exceptional skills in disaster recovery planning, automation scripting, security controls, and technical guidance
WORK EXPERIENCE
Cloud Engineer
03/2022-Present
Cloudscape Solutions
Designed and implemented disaster recovery plans for a major e-commerce platform, reducing downtime by 50% and increasing customer satisfaction by 20%.
Developed and maintained automation scripts for cloud deployments, resulting in a 30% reduction in deployment time and a 25% increase in team productivity.
Provided technical guidance and support to other teams, resulting in a 40% reduction in cloud-related issues and a 15% increase in overall system performance.
Cloud Database Administrator
DataSphere Technologies
03/2020-03/2022
Managed and maintained cloud-based databases for a healthcare organization, ensuring compliance with HIPAA regulations and reducing data breaches by 60%.
Implemented security controls and best practices for cloud environments, resulting in a 75% reduction in security incidents and a 20% increase in customer trust.
Research and evaluated new cloud technologies and services, leading to the adoption of a new cloud provider and a 30% reduction in cloud costs.
Cloud Solutions Engineer
Nimbus Cloud Services
03/2019-03/2020
Designed and implemented cloud-based solutions using AWS, Azure, and GCP for a financial services company, resulting in a 40% increase in system reliability and a 25% reduction in operational costs.
Monitored and optimized cloud infrastructure performance, resulting in a 50% reduction in downtime and a 20% increase in system performance.
Developed and maintained cloud cost optimization strategies, resulting in a 30% reduction in cloud costs and a 15% increase in ROI.
SKILLS & COMPETENCIES
Cloud computing platforms (AWS
evaluation


"""

predict_role(myresume)

'Cloud Engineer'